#!/usr/bin/env bash
dflag=;
vflag=;
cflag=;
sflag=;
if [ "$#" -lt 1 ];
then
  printf "At least one option is required\n";
  printf "Set -s [user@host:path] argument and try again\n";
  exit 2;
fi;

while [ $# -gt 0 ];
do
    case "$1" in
       -d | --description ) 
           dflag=1
           ;;
       -v | --version ) 
           vflag=1
           ;;
       -c | --capabilities ) 
           cflag=1;;
       -s | --ssh ) 
           sflag=1;
           shift;
           uhp=$1;
           ;;
       -h )
           printf "Usage: %s: [--description] [--version] [--capabilities] [--ssh user@host:path]\n" $(basename $0);
           exit 2
           ;;
       * )
           printf "unknown option: %s\n" $1;
           printf "Usage: %s: [--description] [--version] [--capabilities] [--ssh user@host:path]\n" $(basename $0);
           exit 2
           ;;
    esac;
    shift;
done;

if [ "$dflag" ];
then
   path=$(realpath $0);
   printf "$path -s [user@host:path]\n";
fi;
if [ "$vflag" ];
then
   printf "0.1\n";
fi;
if [ "$cflag" ];
then
   printf "baseline\n";
fi;
if [ "$sflag" ];
then
  ssh -q -o ConnectTimeout=120 "${uhp%:*}" "cat ${uhp##*:}";
fi;

exit 0;
